### ISSUE TITLE
service配置NodePort type，nodePort 配置不生效

### ISSUE THREAD

**Issue by zhaopengf** [StarRocks/starrocks-kubernetes-operator#100]
版本：1.6.1
service配置NodePort type，nodePort 配置不生效

**Comment by shileifu** [comment]
怎么访问的，提供一下service的yaml信息

**Comment by zhaopengf** [comment]
apiVersion: starrocks.com/v1alpha1
kind: StarRocksCluster
metadata:
  name: starrockscluster
  namespace: default
spec:
  starRocksFeSpec:
    image: sealos.hub:5000/base/starrocks/alpine-fe:2.5.3
    replicas: 3
    requests:
      cpu: 300m
      memory: 4Gi
    service:
      type: NodePort
      ports:
      - port: 9030
        containerPort: 9030
        nodePort: 30031
    configMapInfo:
      configMapName: fe-config
      resolveKey: fe.conf
    storageVolumes:
      - name: fe-meta-longhorn
        storageClassName: longhorn
        storageSize: 5Gi
        mountPath: /opt/starrocks/fe/meta
      - name: fe-log-longhorn
        storageClassName: longhorn
        storageSize: 5Gi
        mountPath: /opt/starrocks/fe/log
  starRocksBeSpec:
    image: sealos.hub:5000/base/starrocks/centos-be:2.5.3
    replicas: 3
    requests:
      cpu: 300m
      memory: 4Gi
    configMapInfo:
      configMapName: be-config
      resolveKey: be.conf
    storageVolumes:
      - name: be-storage-longhorn
        storageClassName: longhorn
        storageSize: 200Gi
        mountPath: /opt/starrocks/be/storage
      - name: be-log-longhorn
        storageClassName: longhorn
        storageSize: 5Gi
        mountPath: /opt/starrocks/be/log


![图片](https://user-images.githubusercontent.com/46369014/235034608-dd772457-c22a-4109-8637-73698d066749.png)

**Comment by shileifu** [comment]
你的机器和k8s的机器网络通吗，你看一下service的状态是否正常。

**Comment by kevincai** [comment]
take it as done.
