### ISSUE TITLE
StarRocks operator on Red Hat OpenShift as SCC (security context constraints) error. k8s pod security standard

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks-kubernetes-operator#107]
https://github.com/StarRocks/starrocks/issues/22768

**Comment by shileifu** [comment]
the latest image uses the root user. you can seek advise from sida.

**Comment by alberttwong** [comment]
o the issue is that k8s has a pod security standard.  https://kubernetes.io/docs/concepts/security/pod-security-standards/.  openshift enforces it.   so I created a new service account with root-like permissions but I'm still getting issues since our containers run as root, asks for a lot of different type of access, etc etc... basically I don't think we adhere to the policy.

I'm trying various methods to bypass the k8s pod security standard

**Comment by alberttwong** [comment]
https://github.com/StarRocks/starrocks-kubernetes-operator/issues/108

**Comment by alberttwong** [comment]
see https://github.com/StarRocks/starrocks/discussions/22767
