### ISSUE TITLE
starrocks时区设置

### ISSUE THREAD

**Issue by sniperking1234** [StarRocks/starrocks-kubernetes-operator#116]
使用operator安装的时候，是否有方法配置starrocks的时区

**Comment by kevincai** [comment]
try to set "TZ" environment variables by `beEnvVars` or `feEnvVars`. e.g.
```
- name: "TZ"
   value: "Asia/Shanghai"
```

check if this fits your requirement.

**Comment by sniperking1234** [comment]
可以生效
