### ISSUE TITLE
Failure when deploy to Openshift cluster

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#120]
@kevincai 
Deploying FE/BE stateful set fails due to some Security constraint in Openshift. 
Workaround has been provided below but it would be nice to solve this issue in a better way.
```
mv: cannot move '/opt/starrocks/fe/conf/fe.conf' to '/opt/starrocks/fe/conf/fe.conf.bak': Permission denied
ln: failed to create symbolic link '/opt/starrocks/fe/conf/fe.conf': Permission denied
ERROR 2003 (HY000): Can't connect to MySQL server on 'xxxx-fe-service.xxxx:9030' (111)
```
![image](https://github.com/StarRocks/starrocks-kubernetes-operator/assets/5108773/04a486e3-9c71-4ea1-98a8-7fd5cb1a0b8c)

### Workaround
1) add fsGroup: 1000 to both starrocksBeSpec and starrocksFESpec.
E.g.  in the helm values.yaml
```
  starrocksFESpec:
    # Number of replicas to deploy for a fe statefulset.
    replicas: 1
...
    fsGroup: 1000 <======= add this line
```
2) role bind the sa to `system:openshift:scc:anyuid`

deploy the following role binding 
```
> kubectl apply -f rolebinding.yml
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:anyuid
  namespace: you-name-space
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1

subjects:
  - kind: ServiceAccount
    name: your-sa  <============ replace it with the service account you use for starrocks cluster
    namespace: you-name-space <============ replace it with the name space you use for starrocks cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid 
```
cc @imay @hagonzal

**Comment by alberttwong** [comment]
I could not get this to work.

**Comment by alberttwong** [comment]
so modify https://raw.githubusercontent.com/StarRocks/starrocks-kubernetes-operator/main/examples/starrocks/starrocks-fe-and-be.yaml to include `fsGroup: 1000`

**Comment by alberttwong** [comment]
so there are several key items.

1. create a SA (eg. starrocks-sa)
2. assign anyuid to the SA
3. edit the values.ymal to make sure that fsGroup:1000 and serviceAccount: starrocks-sa

then install the helm chart. 

full instructions at https://github.com/StarRocks/starrocks/discussions/22767
