### ISSUE TITLE
be node startup faild for root password changed

### ISSUE THREAD

**Issue by welyss** [StarRocks/starrocks-kubernetes-operator#125]
develop environment, our ceph crash, so must redeploy whole starrocks cluster, at first, there are 5 k8s worker node ready, so 3 fe and 2 be has deployed successfully, then i changed password of root by: ```set password = password('xxx')```, at the time, the 6th k8s worker node has been ready, and operator schedule 3th be to the node, and keep 0/1, check the log: 
```
[Fri Jun  9 05:36:57 UTC 2023] Add myself (starrockscluster-be-2.starrockscluster-be-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
ERROR 1064 (HY000): Access denied for user 'root' (using password: NO)
```
workaround is recover root password to empty, is there any way to deploy successfully cluster without keeping root password empty

**Comment by kevincai** [comment]
check this doc: https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/doc/change_root_password_howto.md

**Comment by welyss** [comment]
ok, thanks
