### ISSUE TITLE
Reconciler error

### ISSUE THREAD

**Issue by lianglijin** [StarRocks/starrocks-kubernetes-operator#131]
E0616 04:34:24.535710       1 cn_controller.go:303] cnController deployAutoscaler failed, namespace=data-analysis,name=data-analysis,version=v2beta2,error=%!s(MISSING)
E0616 04:34:24.535738       1 starrockscluster_controller.go:138] StarRocksClusterReconciler reconcile  sub resource reconcile failed namespace data-analysis name starrocks controller cnController faield no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"
1.6868900645357885e+09	ERROR	Reconciler error	{"controller": "starrockscluster", "controllerGroup": "starrocks.com", "controllerKind": "StarRocksCluster", "StarRocksCluster": {"name":"starrocks","namespace":"data-analysis"}, "namespace": "data-analysis", "name": "starrocks", "reconcileID": "715e2b41-76a1-4b7e-815e-6cf7652d9ac2", "error": "no matches for kind \"HorizontalPodAutoscaler\" in version \"autoscaling/v2beta2\""}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234

**Comment by yandongxiao** [comment]
This is because the `autoscaling/v2beta2` version does not exist. You can run `kubectl api-versions | grep autoscaling` to see the currently supported versions.

**Comment by lianglijin** [comment]
> This is because the `autoscaling/v2beta2` version does not exist. You can run `kubectl api-versions | grep autoscaling` to see the currently supported versions. Currently, `starrocks-kubernetes-operator` does not support modifying the version of HPA.

是啊，我的版本是v1.26.3.

**Comment by yandongxiao** [comment]
I have reproduced the problem you mentioned. Sorry for the previous explanation was wrong, you can specify the version of the HPA object by adding the version field.
```
spec:
  starRocksCnSpec:
    autoScalingPolicy:
      version: v2
```

**Comment by kevincai** [comment]
done
