### ISSUE TITLE
FE、BE 部署时不支持nodeSelector

### ISSUE THREAD

**Issue by xiaolinzi-xl** [StarRocks/starrocks-kubernetes-operator#19]
目前部署环境如下：
- K8s：1.18.10
- starrocks/operator:v1.1、starrocks/fe:2.4.1、starrocks/be:2.4.1

看 API 文档 StarRocksCluster 中不支持加 nodeSelector

**Comment by shileifu** [comment]
node affinity in the supported planning, we will add it as soon as fast, thanks for you question.

**Comment by kevincai** [comment]
done in release v1.3
