### ISSUE TITLE
[Bug] race condition on us BE pods status for the BE CR status

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#196]
There seems to be a potential race condition that one BE pod just finish the upgrade but the next BE pod's upgrade has started, then it will see all BE pods in ready state and  determine the entire cluster in running state for a transient period of time.

https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/pkg/sub_controller/be/be_controller.go#L291-L300

Suggest fix with checking the rollout status. Corresponding kubectl command is:
```
$ kubectl rollout status statefulsets celostar-be -n celostar-test
Waiting for 1 pods to be ready...
```

cc @kevincai

**Comment by kevincai** [comment]
fixed in v1.8.0
