### ISSUE TITLE
restart Annotation on StarRocks Cluster can be removed

### ISSUE THREAD

**Issue by yandongxiao** [StarRocks/starrocks-kubernetes-operator#219]
Annotation on StarRocks Cluster be removed
```
"app.starrocks.fe.io/restart"
"app.starrocks.be.io/restart"
"app.starrocks.cn.io/restart"
```

The recommended practice is that users can add Annotations under FE/BE/CN Spec on their own to trigger the restart of related components.

**Comment by kevincai** [comment]
we have removed this support in v1.8.0, right?

**Comment by yandongxiao** [comment]
not yet
