### ISSUE TITLE
Default username password when BE join FE and when FE electing itself as leader

### ISSUE THREAD

**Issue by adhasahar97** [StarRocks/starrocks-kubernetes-operator#24]
Is there a way to pass the default username and password for FE and BE? Inside the fe_entrypoint.sh and be_entrypoint.sh it is using username: root and password: <blank> as a default. When I change the root password and I increase the number of replica of BE, the BE will fail when it tries to join FE.

```
add_self()
{
    local svc=$1
    start=`date +%s`
    local timeout=$PROBE_TIMEOUT

    while true
    do
        log_stderr "Add myself ($MY_SELF:$HEARTBEAT_PORT) into FE ..."
        timeout 15 mysql --connect-timeout 2 -h $svc -P $FE_QUERY_PORT -u root --skip-column-names --batch -e "ALTER SYSTEM ADD BACKEND \"$MY_SELF:$HEARTBEAT_PORT\";"
        memlist=`show_backends $svc`
        if echo "$memlist" | grep -q -w "$MY_SELF" &>/dev/null ; then
            break;
        fi

        let "expire=start+timeout"
        now=`date +%s`
        if [[ $expire -le $now ]] ; then
            log_stderr "Time out, abort!"
            exit 1
        fi

        sleep $PROBE_INTERVAL

    done
}
```
This line
```timeout 15 mysql --connect-timeout 2 -h $svc -P $FE_QUERY_PORT -u root --skip-column-names --batch -e "ALTER SYSTEM ADD BACKEND \"$MY_SELF:$HEARTBEAT_PORT\";"```

**Comment by kevincai** [comment]
Good point, we are investigating how to mitigate this root password issue in operator deployment case.

**Comment by adhasahar97** [comment]
Hi @kevincai. Do you have update on this?

**Comment by kevincai** [comment]
for a temp workaround, can change the root password instructed by the doc: https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/doc/change_root_password_howto.md

**Comment by kevincai** [comment]
done
