### ISSUE TITLE
好尬,k8s下删除出现hang住的情况

### ISSUE THREAD

**Issue by lijie371** [StarRocks/starrocks-kubernetes-operator#251]
starrocksclusters.starrocks.com/starrocks
使用kubectl delete 删除不了，也没找到对应的日志

**Comment by yandongxiao** [comment]
which operator version do you use?

**Comment by lijie371** [comment]
i solved it by edit starrocksclusters.starrocks.com/starrocks,remove finalizer part.

**Comment by yandongxiao** [comment]
In the latest version, e.g. v1.8.0, the finalizer related logic has been removed. I recommend you use the latest version v1.8.0.
