### ISSUE TITLE
[Feature] Add Configuration for toleration, nodeselector and pod affinity

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#27]
#Context
We need to use the load selector and toleration to deploy SRs to dedicated node group.

```
nodeSelector: {}

tolerations: []

affinity: {}
```

**Comment by kevincai** [comment]
done in release v1.3

**Comment by dengliu** [comment]
@kevincai @shileifu 
are these also supported for the operator deployment?
I don't see it in the helm value template.

**Comment by kevincai** [comment]
@dengliu it is supported in helm even though the helm value template doesn't contain an example.

For example, add the following section in values `starrocksFESpec`
```
  nodeSelector:
    app: starrocks-fe
```
It will generate a `starrockscluster.yaml` with following section
```
spec:
  starRocksFeSpec:
    ...
    nodeSelector:
      app: starrocks-fe
```

These three configurations are supported in helm chart values and applies to FE/BE/CN components.
