### ISSUE TITLE
Allow configure the terminationGracePeriodSeconds via Helm chart 

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#281]
The currently hard-coded 120sec is not enough for core-dump-handler to collect a complete dump when the dumps is big or many crashes happened a the same time

**Comment by dengliu** [comment]
@kevincai 
I did a fio benchmark for the os disk of sequential write of 20GB data of 64KiB blocksize.
The average Write Throughput is ~125MB/s,( I think it is because we are using the very basic tier of gp3 for OS disk).
When  terminationGracePeriodSeconds=120, the theoretical maximum coredump data size can be collected is abut ~15GB.
This is pretty tight for the starrocks BE pod which has the memory setup to 256Gi.

Therefore, without this feature. we cannot collect complete coredump in most of the cases.

**Comment by yandongxiao** [comment]
Please see https://github.com/StarRocks/starrocks-kubernetes-operator/pull/283

**Comment by dengliu** [comment]
> Please see #283

Thanks! Which version of the helm chart has included these changes?

**Comment by yandongxiao** [comment]
v1.8.4 will be released in next one or two weeks
