### ISSUE TITLE
File External Table: CSV file type

### ISSUE THREAD

**Issue by sharon-clue** [StarRocks/starrocks-kubernetes-operator#294]
I have an S3 bucket that has csv files in it
I would like to run a query on top of this.
Currently i see that there's an option to load csv files into StarRocks https://docs.starrocks.io/en-us/3.0/data_source/file_external_table#:~:text=Only%20Parquet%20and%20ORC%20data%20files%20are%20supported.
but not query those files directly

It would be great to have an option to create external tables based on CSV files

**Comment by kevincai** [comment]
@sharon-clue can you move this issue to [starrocks/starrocks](https://github.com/StarRocks/starrocks), it is not related to the kubernetes operator.
