### ISSUE TITLE
StarRocksCluster Configuration Error: Unable to Mount emptyDir Volume at /tmp Path Without Specifying storageSize.

### ISSUE THREAD

**Issue by kapilsingh421** [StarRocks/starrocks-kubernetes-operator#320]
## Describe the bug

When attempting to mount an emptyDir volume with a mount path of /tmp in a StarRocksCluster environment, the system does not seem to recognize or support this configuration. Instead, it appears to only support Persistent Volumes (PV). The configuration used is as follows:

```
- name: {{ .Values.starrocksFESpec.storageSpec.name }}-tmp
  mountPath: /tmp
```
After encountering issues with this setup, I deleted the Custom Resource (CR) and reapplied it, which led to the following error message:

```
StarRocksCluster.starrocks.com "kube-starrocks" is invalid: spec.starRocksFeSpec.storageVolumes[2].storageSize: Required value

```
This error suggests that a storageSize must be provided, indicating a reliance on Persistent Volumes. **However, the requirement is to use emptyDir for the /tmp path.**

## To Reproduce

1. Define a volume mount in the StarRocksCluster configuration to use an emptyDir with a mount path of /tmp.
2. Apply the configuration to the cluster.
3. Observe that the system either does not recognize the configuration or throws an error requiring a storageSize to be specified,           which is indicative of Persistent Volume usage, not emptyDir.**

## Expected behavior

The expected behavior is for the StarRocksCluster to successfully mount an emptyDir volume at the /tmp path without requiring the specification of a storageSize. This would allow for temporary file storage that is not persistent across pod restarts.

## Version

- Operator Version: [ latest]
- Chart Name: [kube-starrocks]

**Comment by kevincai** [comment]
thanks! will take a look how to support this ability.

**Comment by yandongxiao** [comment]
In Kubernetes, PersistentVolumeClaim (PVC) and emptyDir are two different types of volumes, and they cannot be used interchangeably. PVC is used to request storage resources and mount them into a Pod, while emptyDir is a temporary directory created after a Pod is assigned to a node.

**Comment by kapilsilstone** [comment]
Hello @yandongxiao,

I've encountered an issue where our /tmp directory is currently not writable. I'm considering the use of a Persistent Volume (PV) for the frontend /tmp directory to resolve this.

Could you please advise if utilizing a PV for this purpose is a suitable solution? Additionally, if this approach is recommended, what would be the ideal storage size for the PV in this context?

**Comment by yandongxiao** [comment]
Maybe Pull Request (PR) can  be able to be merged this week. You may need to build the container image from the main branch yourself, but it's very simple.

**Comment by yandongxiao** [comment]
https://github.com/StarRocks/starrocks-kubernetes-operator/pull/324
You can try to use this PR
