### ISSUE TITLE
[Feature] Support datadog Log collection from file configured in an annotation

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#41]
Starrocks FE/BE services has multiple sources of logs. It is not appropriate to redirect all logs to `stdout` and `stderr`.
A more proper way is to setup log collection from each log file. This will require adding annotation to the pod spec,  and mount the log files as `hostPath`  volumes.
It would be great to add a config to the helm template with `values.yml` `values.log.enableDatadog` to transparent set up these `annotations` and `hostPath` volumes

Ref: https://docs.datadoghq.com/containers/kubernetes/log/?tab=helm#examples---log-collection-from-file-configured-in-an-annotation

e.g.
```
ad.datadoghq.com/<CONTAINER_IDENTIFIER>.logs: |
  [
    {"type":"file","path":"/opt/starrocks/be/be.INFO","source":"file","service":"starrocks-be"},
    {"type":"file","path":"/opt/starrocks/be/be.WARNING","source":"file","service":"starrocks-be"},
  ]

```
```
ad.datadoghq.com/<CONTAINER_IDENTIFIER>.logs: |
  [
    {"type":"file","path":"/opt/starrocks/fe/fe.log","source":"file","service":"starrocks-fe"},
    {"type":"file","path":"/opt/starrocks/fe/fe.out","source":"file","service":"starrocks-fe"},
    {"type":"file","path":"/opt/starrocks/fe/fe.warn.log","source":"file","service":"starrocks-fe"},
    {"type":"file","path":"/opt/starrocks/fe/fe.audit.log","source":"file","service":"starrocks-fe"},
    {"type":"file","path":"/opt/starrocks/fe/fe.dump.log","source":"file","service":"starrocks-fe"},
  ]    
```

**Comment by shileifu** [comment]
have released in v1.5 operator and v1.5.0 helm.

**Comment by dengliu** [comment]
@shileifu  @kevincai 
In addition to supporting pod annotation, it also needs to support mounting the log dir as `hostPath` volumes.
Is that supported?

**Comment by kevincai** [comment]
log dir can be backed up by a pvc if the log path is configured in `storageVolumeSpec`, or an `emptydir` is provided for it.

**Comment by dengliu** [comment]
Having discussed with @kevincai : it makes more sense to print out all the logs to stdout so we can rely on DD agent to collect it from there.
To be able to differentiate the logs, we could export the logs in json format with customized attributes such as `log_level`, `component`, `stack_trace`.
Here is the instruction to config log4j to  https://docs.datadoghq.com/logs/log_collection/java/?tab=log4j

Here are the  two examples:
```
{
  "@timestamp": "2023-03-31T03:46:50.377Z",
  "@version": "1",
  "message": "Servlet.service() for servlet [dispatcherServlet] in context with path [/celostar-gateway] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause",
  "logger_name": "org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/celostar-gateway].[dispatcherServlet]",
  "thread_name": "http-nio-9777-exec-16",
  "level": "ERROR",
  "level_value": 40000,
  "stack_trace": "java.lang.NullPointerException: null\n\tat java.base/java.util.Objects.requireNonNull(Objects.java:221)\n\tat org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)\n\tat org.springframework.aop.frame\n"
}
```
```
{
  "@timestamp": "2023-03-31T03:46:17.224Z",
  "@version": "1",
  "message": "cleanup inactive loads",
  "logger_name": "com.celonis.celostar.gateway.datamodelload.services.DataModelLoadCleanupService",
  "thread_name": "scheduling-1",
  "level": "INFO",
  "level_value": 20000,
  "cloud-core-version": "15.5.0"
}
```
cc @imay @shileifu

**Comment by dengliu** [comment]
To format the JSON for Datadog, you need to ensure that the JSON output meets the Datadog JSON format requirements. The JSON should contain a "message" field with the log message, and optional fields such as "timestamp", "logger", "level", and "thread".

To adapt the C++ glog library to log in JSON format, you could create a new macro definition that wraps the existing glog library macros and formats the log output as a JSON object. Here's an example of how you could implement this:

```cpp
#define LOG_JSON(LEVEL) \
  LOG(LEVEL) << "{\"message\":\"" << #LEVEL << " message\",\"timestamp\":\"" \
             << std::put_time(std::gmtime(std::time(nullptr)), \
                              "%FT%TZ"), "\"logger\":\"" << FLAGS_log_prefix \
             << "\",\"level\":\"" << #LEVEL << "\",\"thread\":\"" \
             << std::this_thread::get_id() << "\"}"
```
This macro definition creates a new logging macro called LOG_JSON, which takes a logging level as an argument (e.g., INFO, WARNING, etc.) and outputs a log message formatted as a JSON object. The JSON object includes the log message, timestamp, logger name, log level, and thread ID.

You can use this macro in your code like you would use the regular glog macros:
```cpp
LOG_JSON(INFO) << "This is a log message";
```
This will output a log message in JSON format that looks like 
```json
{
    "message": "This is a log message",
    "timestamp": "2022-03-31T10:30:00Z",
    "logger": "myapp",
    "level": "INFO",
    "thread": "main"
}
```

**Comment by kevincai** [comment]
> 

it is not a trivial work to turn glog into json format. it is not the `LOG_JSON` that makes things complicated, but the LOG(XXX) spreads across source files, not mention about the VLOG(X).

We will keep BE glog as plaintext for now until a better solution can be found. E.g. tuning a variable or configuration, and no other code changes. all logs will be outputed as json format.

**Comment by shileifu** [comment]
the operator has supported customized annotations. It's not blocked for the datalog collect log. so closed the issue, if you have any questions please open it.
