### ISSUE TITLE
[Request] Allow/enable deploying sidecar containers with FE to offload functionality

### ISSUE THREAD

**Issue by Hatlassian** [StarRocks/starrocks-kubernetes-operator#411]
## Describe the problem

We would like to be able to offload various functionality on Java UDFs to a WebServer instead, such as caching and parallel processing. This would work by a Java UDF calling webserver to do some processing instead of using the FE nodes to do the processing. While we could deploy this WebServer already, having it running in a separate pod introduces latency and network hops.

## Describe the solution you'd like

If we could deploy this WebServer as a sidecar along with the FE in the same pod, we could have a minimal latency WebServer for offloading this functionality.

**Comment by yandongxiao** [comment]
Currently, adding the sidecar feature is not in our plans, as we have not identified enough scenarios for its use.

**Comment by teddy-hackle** [comment]
I also want this feature.
Because to add AuditLoader in k8s, I need to create a separate zip file with AuditLoader.zip.

Sidecar, such as promtail for collecting additional logs, cannot be added at this time.
