### ISSUE TITLE
starrocks status error

### ISSUE THREAD

**Issue by ymZhao1001** [StarRocks/starrocks-kubernetes-operator#418]
## Describe the bug

1. use starrocks operator to deploy starrocks 

2. service deploy successfully
![image](https://github.com/StarRocks/starrocks-kubernetes-operator/assets/19317643/2edc7ea8-d200-459f-a160-270876aecb11)

3.pod deploy successfully

![image](https://github.com/StarRocks/starrocks-kubernetes-operator/assets/19317643/3ee07651-39bd-4076-802e-73f2713a3ab0)

4. web ui  successfully
![image](https://github.com/StarRocks/starrocks-kubernetes-operator/assets/19317643/b58341f5-a8f0-4466-a351-3bbc2149ce38)

5. mysql connect successfully
![image](https://github.com/StarRocks/starrocks-kubernetes-operator/assets/19317643/1c9d9627-1a35-465d-9a4c-6dbf749edaba)

6. starrocks status error 
![image](https://github.com/StarRocks/starrocks-kubernetes-operator/assets/19317643/b34084be-3bb5-403f-be14-3ef09ce26837)

![image](https://github.com/StarRocks/starrocks-kubernetes-operator/assets/19317643/157f3db0-476a-4788-af27-c2dd744120ec)

## Please complete the following information

- Operator Version: v.1.9.0

starrocks version : 3.1.5 

k8s version: 1.18.3

**Comment by ymZhao1001** [comment]
@yandongxiao  hi, can you help to take a look?

**Comment by yandongxiao** [comment]
I think this issue was fixed recently, Can you try to use operator v1.9.1?
see https://github.com/StarRocks/starrocks-kubernetes-operator/pull/387.

**Comment by ymZhao1001** [comment]
it works! thanks

**Comment by ymZhao1001** [comment]
close issue
