### ISSUE TITLE
StarRocks in Kubernetes should allow to use HostPath for CN nodes' cache

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks-kubernetes-operator#419]
StarRocks in Kubernetes should allow to use HostPath for CN nodes' cache. Using PVCs isn't good hear, especially if I wanna make use of NVMe EC2 instance types. Right now I'm running a cluster of m6id.2xlarge and I had to deploy the Local Volume Provisioner in K8s which isn't trivial, and it also breaks auto-scaling.

@nferrario

**Comment by yandongxiao** [comment]
Could you use 'emptyDir' as CN nodes' cache ? This is the default volumes CN nodes use.

**Comment by nferrario** [comment]
Sadly no. Empty dir uses the root volume of Kubernetes, which in EC2 it would be an EBS backed volume. My goal is to leverage Instance Storage, which offers much lower latency and higher throughput but is ephemeral.
