### ISSUE TITLE
Remove the resource limit in the default value

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#422]
## Describe the bug

We often need to remove the resource limit(especially cpu limit) when deploy to k8s as a good practice.
However because of the[ helm issue](https://github.com/helm/helm/issues/12637). Setting `null` value in the nested value file is not possible.

Therefore the default limit value has to be removed from the parent chart 

## Please complete the following information

- Operator Version: [e.g. v1.8.6]
- Chart Name: [e.g. kube-starrocks]
- Chart Version [e.g. v1.8.6]

**Comment by kevincai** [comment]
its not a good practice for BE to have a unlimited CPU resource. BE will detect number of cpus during the start and some thread pools will create threads linear to the number of cpus. If the limit is not provided, I guess BE process will take whatever it can find, maybe the number of cores of the host CPU. That will cause more trouble than benefits.

Maybe can do some tuning to helm chart templating to allow empty limits for some advanced usage. but the default one should be definitely there.

**Comment by dengliu** [comment]
In our case, we provisioned dedicated node for each BE pod and it is intended to have the BE pod use as much as the CPU resources on the node.
They way that the current helm chart set   `starrocksBeSpec.resources.limits.cpu = 8` which makes it impossible for use to unset it with unlimited by setting it to `starrocksBeSpec.resources.limits.cpu = null` in the cascading values files. e.g. (`helm upgrade starrocks . -n celostar -f values.yaml -f values-eu-dev-1-cs.yaml --render-subchart-notes`) This is due to this [ helm issue](https://github.com/helm/helm/issues/12637).

Setting CPU limits is tricky because containers might underperform due to unexpected and unnecessary throttling. On the other hand, CPU limits are not necessary to prevent CPU starvation on other pods as long as those have set requests! 
Here is another research that suggests this practice with extensive benchmark and research analysis for the curious
[Kubernetes: Make your services faster by removing CPU limits](https://erickhun.com/posts/kubernetes-faster-services-no-cpu-limits)
[CPU limits and aggressive throttling in Kubernetes
](https://medium.com/omio-engineering/cpu-limits-and-aggressive-throttling-in-kubernetes-c5b20bd8a718)

**Comment by yandongxiao** [comment]
I have tried two method, both failed:
1. use `resources.limits.cpu`  directly in `templates/starrockscluster`.
2. use `resources.limits.cpu` in `_helpers.tpl `.

the rendered result always include the default value when I set it to null

**Comment by dengliu** [comment]
> I have tried two method, both failed:
> 
> 1. use `resources.limits.cpu`  directly in `templates/starrockscluster`.
> 2. use `resources.limits.cpu` in `_helpers.tpl `.
> 
> the rendered result always include the default value when I set it to null

I think this is due to this [ helm issue](https://github.com/helm/helm/issues/12637).

**Comment by yandongxiao** [comment]
Yes

> > I have tried two method, both failed:
> > 
> > 1. use `resources.limits.cpu`  directly in `templates/starrockscluster`.
> > 2. use `resources.limits.cpu` in `_helpers.tpl `.
> > 
> > the rendered result always include the default value when I set it to null
> 
> I think this is due to this [ helm issue](https://github.com/helm/helm/issues/12637).

Yes, you are right. I will try to resolve it from operator.

**Comment by yandongxiao** [comment]
Currently, it seems that we can define a special string, for example, "0". When we want to remove the CPU limit, we can configure as follows:
```
resources:
  limits:
    cpu: "0"  # set to "null" is not allowed by decoder
    memory: 2Gi
  requests:
    cpu: 1
    memory: 2Gi
```

By default, if set as above, Kubernetes(e.g. statefulset controller) will throw an error:
```
Invalid value: "xxxm": must be less than or equal to cpu limit of 0
```
`xxxm` is the request value of cpu. This means that the Request Value must be less than or equal to the Limit value.

Solution: The Operator can iterate through the values in limits. If a value is "0", then that configuration can be removed.

**Comment by dengliu** [comment]
why don't we just not set cpu limit in the default (not set it to `null`, just not setting it)?

**Comment by yandongxiao** [comment]
> why don't we just not set cpu limit in the default (not set it to `null`, just not setting it)?

like @kevincai  said, BE will detect number of cpus during the start and some thread pools will create threads linear to the number of cpus, and this is not a good practice.
