### ISSUE TITLE
[Starrocks][Helm] add datadog profiling settings in Helm chart

### ISSUE THREAD

**Issue by mingmxu** [StarRocks/starrocks-kubernetes-operator#423]
## Describe the current behavior

Enabling Datadog profiling in BE/FE pods requires changes in several places, including `podLabels`, multiple environments in `feEnvVars`/`beEnvVars`, `capabilities`. 

## Describe the enhancement

Add a new option in the `datadog` part to enable/disable profiling, and render the settings in Helm template, example like below:
```
datadog:
  log:
    enabled: false
  metrics:
    enabled: false
  profiling:
    fe: false # change to 'true' to enable profiling on FE pods;
    be: false # change to 'true' to enable profiling on BE pods;
```

## Additional context

I would submit a PR if the approach is accepted. 

cc @dengliu

**Comment by yandongxiao** [comment]
LGTM
