### ISSUE TITLE
Add a global `image:tag` field in SR Helm chart

### ISSUE THREAD

**Issue by mingmxu** [StarRocks/starrocks-kubernetes-operator#424]
## Describe the current behavior

Currently every sub-component(`starrocksFESpec`, `starrocksCnSpec`, `starrocksBeSpec`, `starrocksFeProxySpec`) has its own `image:tag` field.  

## Describe the enhancement

Add a new field `starrocksCluster.imageTag` as the default value, the existing one could be kept in case there's a need to override it.

## Additional context

Practically, in one cluster it should always use the same image_tag, built from the same snapshot of code base. It's redundant to set them by sub-component, error-prone to miss one line.

cc @dengliu

**Comment by yandongxiao** [comment]
In the individual spec definitions of the sub-components, there are indeed many fields with the same name, such as image, imagePullSecrets, nodeSelector, schedulerName. Generally, the contents of these fields are consistent in the individual spec definitions of the sub-components. Of course, it would be better if a way could be found to set default values uniformly.

**Comment by yandongxiao** [comment]
work on it.

**Comment by dengliu** [comment]
`nodeSelector` can be different as FE and BE usually require different node spec.
