### ISSUE TITLE
Make the default value of `feEnvVars` `beEnvVars`  to `[]` to eliminate the helm warning

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#430]
## Describe the current behavior
When use helm upgrade with `feEnvVars` `beEnvVars` being overridden with map value. Helm report the following warning.
The reason is because the default value of  `feEnvVars` `beEnvVars` are set to `[]`
[starrocks-kubernetes-operator/blob/main/helm-charts/charts/kube-starrocks/values.yaml#L252](https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/helm-charts/charts/kube-starrocks/values.yaml#L252) 
```
helm upgrade starrocks . -n celostar  -f values.yaml -f values-eu-dev-1-cs.yaml 
...
coalesce.go:289: warning: destination for celostar-starrocks.starrocks.starrocksBeSpec.beEnvVars is a table. Ignoring non-table value ([])
coalesce.go:289: warning: destination for celostar-starrocks.starrocks.starrocksFESpec.feEnvVars is a table. Ignoring non-table value ([])
coalesce.go:289: warning: destination for celostar-starrocks.starrocks.starrocksFESpec.feEnvVars is a table. Ignoring non-table value ([])
coalesce.go:289: warning: destination for celostar-starrocks.starrocks.starrocksBeSpec.beEnvVars is a table. Ignoring non-table value ([])
```

helm versoion
`version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.5"}
`

## Describe the enhancement

Make the default value to `[]` to eliminate the helm warning
## Additional context

Add any other context or screenshots about the enhancement here.

**Comment by yandongxiao** [comment]
I think what your suggestion is: Make the default value to {} to eliminate the helm warning, not [] ?

**Comment by dengliu** [comment]
> I think what your suggestion is: Make the default value to {} to eliminate the helm warning, not [] ?

yes.

**Comment by mingmxu** [comment]
+1 to have a default value `{}`
