### ISSUE TITLE
helm operation failure when `config-hash` has numbers only

### ISSUE THREAD

**Issue by mingmxu** [StarRocks/starrocks-kubernetes-operator#478]
## Describe the bug

For all the `app.starrocks.io/xx-config-hash` fields, when the hash string has numbers only. Helm operation fails with error message:
> Error: UPGRADE FAILED: failed to create resource: StarRocksCluster.starrocks.com "celostar" is invalid: spec.starRocksBeSpec.annotations.app.starrocks.io/be-config-hash: Invalid value: "integer": spec.starRocksBeSpec.annotations.app.starrocks.io/be-config-hash in body must be of type string: "integer"

## To Reproduce

build a configmap which has hash value in numbers only, see the function code [here](https://github.com/StarRocks/starrocks-kubernetes-operator/blob/5f93b29d27eea8cbb22bddfb39d785f6d88b1436/helm-charts/charts/kube-starrocks/charts/starrocks/templates/_helpers.tpl#L196).

## Expected behavior

helm should work

## Please complete the following information

- Operator Version: [v1.9.2]
- Chart Name: [kube-starrocks]
- Chart Version [v1.9.2]

cc @dengliu @yandongxiao

**Comment by mingmxu** [comment]
Refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
> The keys and the values in the map must be strings.

It seems that Kubernetes can convert it implicitly in the right way if there're non-numeric characters, so the workaround suggestion is to make a dummy change in `config` to generate a 'valid' hash string.

**Comment by yandongxiao** [comment]
Can you please do a quick review about it ?
