### ISSUE TITLE
expose `admission.datadoghq.com/config.mode` in helm values

### ISSUE THREAD

**Issue by mingmxu** [StarRocks/starrocks-kubernetes-operator#481]
## Describe the current behavior

It's hard code for datadog profiling, see code line [here](https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml#L290C7-L290C42)

> admission.datadoghq.com/config.mode: service

## Describe the enhancement

Expose it to be configurable so users could choose the best mode for their own deployment environment.

## Additional context

In Datadog, there're three modes, see the doc [here](https://docs.datadoghq.com/containers/cluster_agent/admission_controller/?tab=operator#configure-apm-and-dogstatsd-communication-mode). Recently we run into an issue that many kubernetes tags are lost, it's advised(and we confirmed the solution) by Datadog support team to use `mode: socket` to fix the issue.

**Comment by yandongxiao** [comment]
Since you brought up the previous PR, can you help solve this issue?

**Comment by mingmxu** [comment]
cc @yandongxiao there's the fix https://github.com/StarRocks/starrocks-kubernetes-operator/pull/482
