### ISSUE TITLE
[helm]support config override in starrocksFESpec/starrocksBeSpec/starrocksCnSpec

### ISSUE THREAD

**Issue by mingmxu** [StarRocks/starrocks-kubernetes-operator#494]
## Describe the current behavior

Currently all the `config` in starrocks helm chart are taken as a block, see the code [here](https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/helm-charts/charts/kube-starrocks/charts/starrocks/templates/_helpers.tpl#L53-L72). As a result, partial update is not supported.

## Describe the enhancement

Support partial update in `values.yaml` to simplify configuration changes. 

## Additional context

cc @dengliu @yandongxiao

**Comment by yandongxiao** [comment]
‌‌The "partial update" you mentioned refers to adding or updating some additional configurations in other values.yaml files on top of a certain base values.yaml configuration?

**Comment by mingmxu** [comment]
> ‌‌The "partial update" you mentioned refers to adding or updating some additional configurations in other values.yaml files on top of a certain base values.yaml configuration?

Yes,

**Comment by yandongxiao** [comment]
This is a bit challenging because the current type of config is a string. We need to parse this string in _helper, convert it into the format of a map, and finally merge it with the default values. I tried to write it, but failed.
