### ISSUE TITLE
[Bug] changing resource request value doesn't trigger updating of StarRocks cluster

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#50]
@shileifu  @kevincai 

If I make a change to the resource specifications in the values.yml file, such as increasing the requested CPU from 2 to 3, without changing the number of replicas, upgrading the Helm release will not trigger an upgrade of the pod. However, if I increase the number of replicas from 3 to 4, all pods will receive the updated resource specifications.

**Comment by shileifu** [comment]
I use helm is ok ,can you share me more informatins.

**Comment by shileifu** [comment]
sorry, the new version is 1..3.5

**Comment by shileifu** [comment]
the version ok ?

**Comment by dengliu** [comment]
Yep. just verified that changing either the resource request/limit or the nodeSelector in the values.yaml will trigger a update of the pods.
Thanks for the fix!
