### ISSUE TITLE
‌‌‌‌‌‌‌FE Proxy can be deployed together with BE in a sidecar manner.

### ISSUE THREAD

**Issue by yandongxiao** [StarRocks/starrocks-kubernetes-operator#507]
‌FE Proxy is used in Stream Load scenarios. When importing a particularly large throughput, additional computing resources need to be provided to FE Proxy. Deploying FE Proxy together with BE can reduce the demand for resources.

**Comment by kevincai** [comment]
what's the benefits of doing so?

feproxy proxies fe's http request to a BE/CN node, the node may not be the one it colocated with.

**Comment by yandongxiao** [comment]
‌‌Yes, I later considered this and turned it off.
