### ISSUE TITLE
FE proxy works for loading data with the spark connector, but not for unloading

### ISSUE THREAD

**Issue by snippins** [StarRocks/starrocks-kubernetes-operator#523]
After deploy starrocks on k8s (shared-data mode) with feproxy, I was able to write data to starrocks with spark, however, I was unable to unload (reading) the data with the spark connector. Checking the log from spark, it appears that the connector still trying to connect directly to cn nodes and failed.

The error  looks something like this:

`com.starrocks.shade.org.apache.thrift.transport.TTransportException: java.net.UnknownHostException: starrocks-cluster-cn-0.starrocks-cluster-cn-search.starrocks.svc.cluster.local
`

I'm currently using starrocks 3.2.4

**Comment by yandongxiao** [comment]
Currently, the FE Proxy primarily acts as a proxy for Stream Load requests. It addresses the issue where clients outside of k8s are unable to recognize k8s service domain names.

Regarding the problem you mentioned, I think it should still be a domain name resolution issue; the FE Proxy does not yet support handling Thrift requests.

**Comment by snippins** [comment]
So as I understand, this use case for spark connecting from outside of the starrocks k8s cluster is not yet supported, right? 

I think the docs should mention this, also as a workaround I'm currently using [INSERT INTO FILES](https://docs.starrocks.io/docs/unloading/unload_using_insert_into_files/), and then use spark to load data from the exported files.

**Comment by yandongxiao** [comment]
sure, will update doc
