### ISSUE TITLE
[Bug] setting starrocksFESpec.beEnvVars doesn't taking effect

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#56]
The setting of `starrocksFESpec.beEnvVars doesn't taking effect`
![image](https://user-images.githubusercontent.com/5108773/222834474-344f8de1-db10-4afa-bdb0-89b7e5a9e9f0.png)

**Comment by kevincai** [comment]
this issue is fixed in helm chart release v1.3.4. Please upgrade the helm chart to v1.3.4
