### ISSUE TITLE
exec /sroperator: exec format error

### ISSUE THREAD

**Issue by nickscut** [StarRocks/starrocks-kubernetes-operator#566]
## Describe the bug

+ kubectl logs kube-starrocks-operator-86bfb4c868-v69vx
exec /sroperator: exec format error

Linux iZbp1i8lh3zggfpl1t1fohZ 3.10.0-1160.108.1.el7.x86_64 #1 SMP Thu Jan 25 16:17:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

## Please complete the following information

- Operator Version: [ v1.9.7]
- Chart Name: [kube-starrocks]
- Chart Version [ v1.9.7]

**Comment by kevincai** [comment]
can you describe the operator pod, need to get the sha256 of the operator image.

**Comment by nickscut** [comment]
+ kubectl describe pod kube-starrocks-operator-86bfb4c868-c8fgl
Name:             kube-starrocks-operator-86bfb4c868-c8fgl
Namespace:        default
Priority:         0
Service Account:  starrocks
Node:             izbp1i8lh3zggfpl1t1fohz/172.16.0.230
Start Time:       Thu, 11 Jul 2024 12:10:37 +0800
Labels:           app=kube-starrocks-operator
                  pod-template-hash=86bfb4c868
                  version=1.9.7
Annotations:      kubectl.kubernetes.io/default-container: manager
Status:           Running
IP:               10.42.0.34
IPs:
  IP:           10.42.0.34
Controlled By:  ReplicaSet/kube-starrocks-operator-86bfb4c868
Containers:
  manager:
    Container ID:  docker://563a8d30195ab3c3894171faa622ec0b69c9ef0b5e1d4a3788b4acb94754e741
    Image:         starrocks:operator-v1.9.6
    Image ID:      docker-pullable://starrocks@sha256:69db6496ef62361c414b2e4822716cd86db5d72ccdba37495e087b02e7594bb4
    Port:          <none>
    Host Port:     <none>
    Command:
      /sroperator
    Args:
      --leader-elect
      --zap-time-encoding=iso8601
      --zap-encoder=console
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 11 Jul 2024 12:11:31 +0800
      Finished:     Thu, 11 Jul 2024 12:11:31 +0800
    Ready:          False
    Restart Count:  3
    Limits:
      cpu:     500m
      memory:  800Mi
    Requests:
      cpu:      500m
      memory:   400Mi
    Liveness:   http-get http://:8081/healthz delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:  http-get http://:8081/readyz delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TZ:  Asia/Shanghai
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-d6d82 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-d6d82:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  76s                default-scheduler  Successfully assigned default/kube-starrocks-operator-86bfb4c868-c8fgl to izbp1i8lh3zggfpl1t1fohz
  Normal   Pulled     22s (x4 over 76s)  kubelet            Container image "starrocks:operator-v1.9.6" already present on machine
  Normal   Created    22s (x4 over 76s)  kubelet            Created container manager
  Normal   Started    22s (x4 over 76s)  kubelet            Started container manager
  Warning  BackOff    1s (x9 over 74s)   kubelet            Back-off restarting failed container manager in pod kube-starrocks-operator-86bfb4c868-c8fgl_default(46affc5a-ffa9-4a6a-bed7-98b163364b10)

**Comment by kevincai** [comment]
didn't see the sha256 digest matches any of the images in the dockerhub, did you build the image yourself?

![image](https://github.com/StarRocks/starrocks-kubernetes-operator/assets/771299/058a713a-ce7c-45a5-90af-93ebfe713a46)

**Comment by nickscut** [comment]
I pulled it from the local repository and then pushed it to our own repository.

Our machines cannot access https://hub.docker.com/.

**Comment by nickscut** [comment]
i see，i will try other way

**Comment by yandongxiao** [comment]
If you pulled it to your local machine, `docker pull` will only pull the needed platform.
