### ISSUE TITLE
Add annotations for FE Proxy service

### ISSUE THREAD

**Issue by snowsky** [StarRocks/starrocks-kubernetes-operator#570]
## Describe the bug

Other services other than FE Proxy service have `annotations` parameter. I tested loadBalancerSourceRanges, but I didn't make it work. Is it possible to add `annotations` to FE Proxy service?

**Comment by yandongxiao** [comment]
‌‌It seems you are using a helm chart to deploy StarRocks. From the implementation perspective, the Operator already supports 'annotations' and 'loadBalancerSourceRanges' features.
The following `values.yaml` definition indicates that the helm chart does not support 'annotations'.
https://github.com/StarRocks/starrocks-kubernetes-operator/blob/8b2bd10eac17f0a218a47cba8c6fa7c50fe95e2b/helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml#L967-L982

**Comment by yandongxiao** [comment]
‌‌‌Making the Helm chart support annotations is relatively straightforward. Could you describe why you need to add Service Annotations in the FE proxy ?

**Comment by snowsky** [comment]
Thanks for the updates. I'd like to customize the security group for FE Proxy with annotations 👍
