### ISSUE TITLE
[Bug] Updating config should trigger restarting the pod

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#68]
At present, modifying `starrocksBeSpec.config` and `starrocksFESpec.config` merely updates the configmap without restarting the pod, thereby config changes fails to take effect. 
The correct approach shall updating the configmap and restarting the pod to effectuate the updated configuration.

**Comment by dengliu** [comment]
@kevincai @shileifu can you please add this issue?
Thank you!

**Comment by shileifu** [comment]
@dengliu the ability will be provided in the next operator version, the CRD version v1.

**Comment by shileifu** [comment]
the ability has been supported in v1.6. we closed the issue, any questions about the ability can reopen it.
