### ISSUE TITLE
Support Red Hat UBI-8 for base container image

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks-kubernetes-operator#70]
The issue is around container support.   Support isn't provided on the container level, it's done on the host level.   So Suse will not support (provide big fixes, etc etc) for a Red Hat container (only best effort).    So when there are issues between the container (different linux distro) and host (another different linux distro), you have finger pointing on who should fix what.   The biggest on prem market is Red Hat.    

https://www.redhat.com/en/blog/limits-compatibility-and-supportability-containers

**Comment by kevincai** [comment]
ubi based container images are provided as `starrocks/fe-ubi`, `starrocks/be-ubi`, `starrocks/cn-ubi`.

**Comment by alberttwong** [comment]
Thanks!   I'll try it out.
