### ISSUE TITLE
What is the target Operator Capability Level?

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks-kubernetes-operator#71]
What isn't said in the README is what is the target Operator Capability Level for this operator.   https://sdk.operatorframework.io/docs/overview/operator-capabilities/

**Comment by shileifu** [comment]
yes, level1-level3 we have supported. level 4 will be finished next week.  autoscaler we only support cn service. cn is the compute node.

**Comment by alberttwong** [comment]
Can we list what are the capabilities that map to the suggestion features in the operator levels? https://sdk.operatorframework.io/docs/overview/operator-capabilities/

**Comment by kevincai** [comment]
level 2 for now. will add doc to list the capabilities.
