### ISSUE TITLE
Add StarRocksBeSpec and StarRocksFeSpec Pod Template

### ISSUE THREAD

**Issue by zorrofox** [StarRocks/starrocks-kubernetes-operator#87]
Hi,
if we can add `StarRocksBeSpec` and `StarRocksFeSpec` for pod template support will more flexibility for the Operator deployment such as we can use some sidecar to collect StarRocks logs.

**Comment by zorrofox** [comment]
@kevincai Thanks! I will try it.

**Comment by zorrofox** [comment]
> start from fe/be/cn 3.0.0-rc02, we support logging to console, so the generic logging collection can be applied fe/be pod.
> 
> try enable the console logging by setting envVar 'LOG_CONSOLE=1'
> 
> e.g.
> 
> ```yaml
> beEnvVars:
> - name: "LOG_CONSOLE"
>   value: "1"
> ```

I have tested this config, and it always run into crash in my Kubernetes env. I don't know why.

**Comment by kevincai** [comment]
are you able to get any console log before FE crash?

**Comment by zorrofox** [comment]
No, I think it maybe crash before the log can be output, and I cannot enter into the POD to debug.

**Comment by kevincai** [comment]
if enabled with LOG_CONSOLE, all the logs will be printed to console, you can use `kubectl logs <pod>` to check the log output. there will be at least some logging simliar to follows

```
[Fri Apr 14 14:56:01 UTC 2023] Process conf file fe.conf ...
[Fri Apr 14 14:56:01 UTC 2023] first start fe with meta not exist.
ERROR 2003 (HY000): Can't connect to MySQL server on 'ictest-fe-service.kc' (111)
```

**Comment by zorrofox** [comment]
> 

Yes, I can these logs but when sometime go the docker crash again and again.

**Comment by kevincai** [comment]
use `kubectl logs -f <podname>` to see the last a few lines before the crash, then check if need to enter the container to grap more logs for analysis.

**Comment by kevincai** [comment]
take it as completed.
