### ISSUE TITLE
deployed CRD error

### ISSUE THREAD

**Issue by huldarchen** [StarRocks/starrocks-kubernetes-operator#93]
k8s version: v1.24.8
An error occurred while adding custom resources
`kubectl apply -f https://raw.githubusercontent.com/StarRocks/starrocks-kubernetes-operator/main/deploy/starrocks.com_starrocksclusters.yaml`
error msg is
`The CustomResourceDefinition "starrocksclusters.starrocks.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

**Comment by shileifu** [comment]
please use kubectl replace -f  https://raw.githubusercontent.com/StarRocks/starrocks-kubernetes-operator/main/deploy/starrocks.com_starrocksclusters.yaml

**Comment by huldarchen** [comment]
> please use kubectl replace -f https://raw.githubusercontent.com/StarRocks/starrocks-kubernetes-operator/main/deploy/starrocks.com_starrocksclusters.yaml
It's not work
![image](https://user-images.githubusercontent.com/41148123/232995628-4fadb1d8-3dd9-466d-af81-98df658fe2ba.png)

**Comment by kevincai** [comment]
if you haven't created the crd before in the cluster.

please use `kubectl create -f ...`

**Comment by huldarchen** [comment]
> if you haven't created the crd before in the cluster.
> 
> please use `kubectl create -f ...`

It's work. thanks.
Is the deployment documentation wrong?
[deploy-starrocks-operator](https://docs.starrocks.io/en-us/latest/administration/sr_operator#deploy-starrocks-operator)
<img width="847" alt="image" src="https://user-images.githubusercontent.com/41148123/233001179-efa8f9d7-fd0f-478c-983a-6b4448754456.png">

**Comment by kevincai** [comment]
no `kubectl apply` works for most case, and is the safe option to run, but can run to corner cases when the yaml is too big, as we talked about in this issue.

**Comment by huldarchen** [comment]
Ok, then this issue can be closed, thanks.
