### ISSUE TITLE
能把在k8s中部署的FE+CN加入到外部已有的集群中么

### ISSUE THREAD

**Issue by humingxu** [StarRocks/starrocks-kubernetes-operator#94]
已有了一套物理机集群(FE+BE)，想借助k8s部署CN实现计算弹性伸缩，如何将k8s集群中的FE+CN add进物理机集群中呢

**Comment by kevincai** [comment]
需要先解决网络连通性的问题. k8s里的CN与物理集群的FE能互相连通.

**Comment by humingxu** [comment]
网络是通的，麻烦接下来该如何操作呢

**Comment by kevincai** [comment]
需要很多手动操作. 你不如部署先部署一个出来, 然后把statefulset里的xxx-be yaml复制出来, 再改成和你的物理机FE集群连通的地方. 

1) FE_SERVICE_NAME, 换成FE的IP地址
2) BE/CN的部署模式HOST_TYPE根据你的FE部署方式, 改成IP或者FQDN, 需要保持与FE启动时选择的type一致.

**Comment by humingxu** [comment]
这个没有找到在哪里设置，能帮忙给个截个图给个例子么？
1.FE_SERVICE_NAME, 换成FE的IP地址

**Comment by shileifu** [comment]
你可以根据computenodegroup分支，自己制作镜像部署。

**Comment by shileifu** [comment]
没有额外的限制。那个分支能力是腾讯teg和ieg团队帮忙贡献的能力，自动扩缩容是基于v2beta2的autoscaler.

**Comment by humingxu** [comment]
我们物理集群的FE/BE是2.5.3版本，使用computenodegroup制作CN镜像部署，支持autoscale么？稳定么

**Comment by kevincai** [comment]
@huldarchen 是的, FE_SERVICE_NAME改成外部FE LEADER IP. HOST_TYPE按外部FE部署模式进行修改. 密码无法修改. 默认是空密码, 否则弹出的节点不能自动加入到集群里.

**Comment by kevincai** [comment]
https://github.com/StarRocks/starrocks/blob/main/docker/dockerfiles/fe/fe_entrypoint.sh

**Comment by humingxu** [comment]
代码里是怎么引用的，没有找到引用的入口

**Comment by kevincai** [comment]
引用是指?

**Comment by humingxu** [comment]
我们想引用自定义的fe_entrypoint.sh、cn_entrypoint.sh文件，在哪里修改下代码呢

**Comment by kevincai** [comment]
这个? https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/pkg/sub_controller/cn/cn_pod.go#L111

**Comment by huldarchen** [comment]
> @kevincai 麻烦问下，fe_entrypoint.sh、cn_entrypoint.sh文件是在哪里定义的，在项目中没有找到这2个文件。 对于您上面说的密码无法修改，我们目前的做法是做了个init容器，作用是会将我们自定义的fe_entrypoint.sh、cn_entrypoint.sh文件(修改了密码) 覆盖原有的这2个文件。

可以参考下你们的init容器么？

**Comment by kevincai** [comment]
done
