### ISSUE TITLE
k8 operator. unable to validate against any security context constraint

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks-kubernetes-operator#95]
https://github.com/StarRocks/starrocks/issues/21974

**Comment by kevincai** [comment]
should be fixed in latest operator, set fsGroup: 0 to disable nonroot user setup. I will setup my openshift account and validate it.

**Comment by alberttwong** [comment]
hmm.. where do I get the latest? I think I am using the latest.

**Comment by atiwary91** [comment]
@kevincai Could you please help Albert? Does he need to update the Openshift platform? He is using RHPDS to test his operator

**Comment by kevincai** [comment]
> @kevincai Could you please help Albert? Does he need to update the Openshift platform? He is using RHPDS to test his operator

I managed to force use uid:0 to run the application, however, openshift seems auto injected securityContext if the pod spec doesn't contain any security context settings. Could be something related to https://docs.openshift.com/container-platform/3.11/admin_guide/manage_scc.html#modify-cluster-default-behavior
